# Generated by Django 5.2.5 on 2025-11-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_vehicle_created_at_alter_vehicle_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedvehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_saved_vehicles', to='Users.userprofile'),
        ),
    ]
