# Generated by Django 5.2.5 on 2025-11-03 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_savedvehicle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userprofile'),
        ),
        migrations.DeleteModel(
            name='SavedVehicle',
        ),
    ]
