# Generated by Django 4.2.23 on 2025-11-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_vehicle_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(default='petrol', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_coordinates',
            field=models.CharField(default='207848 678594', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.PositiveIntegerField(default=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(default='manuel', max_length=20),
            preserve_default=False,
        ),
    ]
