# Generated by Django 4.2.23 on 2025-11-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_vehicle_fuel_type_vehicle_gps_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='contact',
            field=models.CharField(default='00000000', max_length=20),
            preserve_default=False,
        ),
    ]
