# Generated by Django 4.2.23 on 2025-11-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_vehicle_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
