# Generated by Django 5.2.5 on 2025-11-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
        ('Users', '0003_alter_savedvehicle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedvehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_saved_vehicles', to='Users.userprofile'),
        ),
    ]
