# Generated by Django 4.2.23 on 2025-11-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0006_alter_vehicle_fuel_type_alter_vehicle_transmission_and_more'),
        ('Profile', '0003_alter_savedvehicle_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedVehicle',
            fields=[
            ],
            options={
                'verbose_name': 'Uploaded Vehicle',
                'verbose_name_plural': 'Uploaded Vehicles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Vehicles.vehicle',),
        ),
    ]
