# Generated by Django 4.2.23 on 2025-10-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type_of_vehicle',
            field=models.CharField(choices=[('Car', 'Car'), ('Truck', 'Truck'), ('Van', 'Van'), ('SUV', 'SUV'), ('Motorbike', 'Motorbike'), ('Bus', 'Bus')], max_length=50),
        ),
    ]
