# Generated by Django 5.2.5 on 2025-10-17 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0002_alter_vehicle_price_alter_vehicle_type_of_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_vehicles', to=settings.AUTH_USER_MODEL),
        ),
    ]
