# Generated by Django 5.2.5 on 2025-11-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0004_vehicle_latitude_vehicle_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='longitude',
        ),
    ]
