# Generated by Django 4.2.23 on 2025-11-07 16:24

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0005_remove_vehicle_latitude_remove_vehicle_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric'), ('Other', 'Other')], default='Petrol', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('CVT', 'CVT'), ('Other', 'Other')], default='Manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type_of_vehicle',
            field=models.CharField(choices=[('Car', 'Car'), ('Truck', 'Truck'), ('Van', 'Van'), ('SUV', 'SUV'), ('Motorbike', 'Motorbike'), ('Bus', 'Bus')], default='Car', max_length=50),
        ),
    ]
