# Generated by Django 5.2.5 on 2025-11-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0006_alter_vehicle_fuel_type_alter_vehicle_transmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
