# Generated by Django 5.2.5 on 2025-11-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0007_vehicle_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
